language: python
python:
  # We don't actually use the system Python but this keeps it organized.
  - "2.7"
  - "3.3"
  - "3.4"
install:
  # TODO: Use a "latest" url
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.5.2-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.5.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda install requests
  - cd ..
  - git clone git://github.com/conda/conda
  - cd conda
  - python setup.py install
  - conda info -a
  - cd ../conda-api
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - python setup.py install

script: py.test test.py

notifications:
    flowdock: ef3821a08a791106512ccfc04c92eccb
